### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by olokobayusuf** [WeTransfer/wt-js-sdk#204]
**Is your feature request related to a problem? Please describe.**
Not a problem. Typescript is pretty common nowadays, so it'll be great to have typings for it.

**Describe the solution you'd like**
`typings.d.ts`

**Describe alternatives you've considered**
Using the SDK without typings in TypeScript.

**Additional context**
None.

**Comment by olokobayusuf** [comment]
I've started working on some rudimentary typings. I'll create a PR soon.

**Comment by arkaitzgarro** [comment]
@olokobayusuf that's amazing. Thank you so much!

**Comment by seelts** [comment]
That's nice!

**Comment by olokobayusuf** [comment]
WIP in #206

**Comment by seelts** [comment]
#206 is merged!
We have typings now!
Amazing! 🎉

**Comment by arkaitzgarro** [comment]
Thank you very much indeed @olokobayusuf
